from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import random, sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        '''настройки шрифта главного'''
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        '''настройки окна'''
        MainWindow.setFont(font)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 800)
        MainWindow.setWindowTitle("Грустный песик")
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        '''настройки спец штук'''
        self.wordstat = QtWidgets.QLabel(self.centralwidget)
        self.wordstat.setGeometry(QtCore.QRect(245, 170, 600, 70))
        font.setPointSize(20)
        self.wordstat.setFont(font)
        self.wordstat.setScaledContents(False)
        self.wordstat.setAlignment(QtCore.Qt.AlignCenter)
        self.wordstat.setObjectName("wordstat")
        self.help5050 = QtWidgets.QPushButton(self.centralwidget)
        self.help5050.setGeometry(QtCore.QRect(360, 700, 101, 41))
        font.setPointSize(18)
        self.help5050.setFont(font)
        self.help5050.setFlat(True)
        self.help5050.setObjectName("help5050")
        self.helps = QtWidgets.QLabel(self.centralwidget)
        self.helps.setGeometry(QtCore.QRect(480, 670, 111, 31))
        font.setPointSize(15)
        self.helps.setFont(font)
        #self.helps.setStyleSheet("background-image: url(:/bck/grass.jpg);")
        self.helps.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.helps.setFrameShadow(QtWidgets.QFrame.Plain)
        self.helps.setAlignment(QtCore.Qt.AlignCenter)
        self.helps.setObjectName("helps")
        self.tryletter = QtWidgets.QPushButton(self.centralwidget)
        self.tryletter.setGeometry(QtCore.QRect(480, 700, 251, 41))
        font.setPointSize(18)
        self.tryletter.setFont(font)
        #self.tryletter.setStyleSheet("background-image: url(:/bck/grass.jpg);")
        self.tryletter.setFlat(True)
        self.tryletter.setObjectName("tryletter")
        self.numstr1 = QtWidgets.QPushButton(self.centralwidget)
        self.numstr1.setGeometry(QtCore.QRect(250, 750, 181, 41))
        self.numstr1.setFont(font)
        #self.numstr1.setStyleSheet("background-image: url(:/bck/grass.jpg)")
        self.numstr1.setFlat(True)
        self.numstr1.setObjectName("numstr1")
        self.numstr2 = QtWidgets.QPushButton(self.centralwidget)
        self.numstr2.setGeometry(QtCore.QRect(450, 750, 181, 41))
        self.numstr2.setFont(font)
        #self.numstr2.setStyleSheet("background-image: url(:/bck/grass.jpg)")
        self.numstr2.setFlat(True)
        self.numstr2.setObjectName("numstr2")
        self.numstr3 = QtWidgets.QPushButton(self.centralwidget)
        self.numstr3.setGeometry(QtCore.QRect(650, 750, 181, 41))
        self.numstr3.setFont(font)
        #self.numstr3.setStyleSheet("background-image: url(:/bck/grass.jpg)")
        self.numstr3.setFlat(True)
        self.numstr3.setObjectName("numstr3")
        self.choosedif = QtWidgets.QLabel(self.centralwidget)
        self.choosedif.setGeometry(QtCore.QRect(400, 280, 281, 51))
        font.setPointSize(20)
        self.choosedif.setFont(font)
        #self.choosedif.setStyleSheet("background-image: url(:/bck/yellow.jpg);")
        self.choosedif.setObjectName("choosedif")
        self.difftext = QtWidgets.QLabel(self.centralwidget)
        self.difftext.setGeometry(QtCore.QRect(360, 410, 341, 101))
        font.setPointSize(12)
        self.difftext.setFont(font)
        #self.difftext.setStyleSheet("background-image: url(:/bck/yellow.jpg);")
        self.difftext.setObjectName("difftext")
        self.trystat = QtWidgets.QLabel(self.centralwidget)
        self.trystat.setGeometry(QtCore.QRect(870, 10, 171, 31))
        font.setPointSize(20)
        self.trystat.setFont(font)
        self.trystat.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.trystat.setObjectName("trystat")
        self.easybtn = QtWidgets.QPushButton(self.centralwidget)
        self.easybtn.setGeometry(QtCore.QRect(280, 350, 151, 41))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.easybtn.setFont(font)
        self.easybtn.setFlat(True)
        self.easybtn.setObjectName("easybtn")
        self.normbtn = QtWidgets.QPushButton(self.centralwidget)
        self.normbtn.setGeometry(QtCore.QRect(460, 350, 151, 41))
        self.normbtn.setFont(font)
        self.normbtn.setFlat(True)
        self.normbtn.setObjectName("normbtn")
        self.hardbtn = QtWidgets.QPushButton(self.centralwidget)
        self.hardbtn.setGeometry(QtCore.QRect(630, 350, 151, 41))
        self.hardbtn.setFont(font)
        self.hardbtn.setFlat(True)
        self.hardbtn.setObjectName("hardbtn")
        self.Abtn = QtWidgets.QPushButton(self.centralwidget)
        self.Abtn.setGeometry(QtCore.QRect(250, 10, 51, 51))

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1081, 801))
        self.label.setPixmap(QtGui.QPixmap("bck1.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 240, 941, 431))
        self.label_2.setPixmap(QtGui.QPixmap("10try.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        '''настройки кнопок алфавита'''
        font.setBold(False)
        font.setPointSize(14)
        self.Abtn.setFont(font)
        self.Abtn.setFlat(True)
        self.Abtn.setObjectName("Abtn")
        self.Bbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Bbtn.setGeometry(QtCore.QRect(300, 10, 51, 51))
        self.Bbtn.setFont(font)
        self.Bbtn.setFlat(True)
        self.Bbtn.setObjectName("Bbtn")
        self.Vbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Vbtn.setGeometry(QtCore.QRect(350, 10, 51, 51))
        self.Vbtn.setFont(font)
        self.Vbtn.setFlat(True)
        self.Vbtn.setObjectName("Vbtn")
        self.Gbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Gbtn.setGeometry(QtCore.QRect(400, 10, 51, 51))
        self.Gbtn.setFont(font)
        self.Gbtn.setFlat(True)
        self.Gbtn.setObjectName("Gbtn")
        self.Dbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Dbtn.setGeometry(QtCore.QRect(450, 10, 51, 51))
        self.Dbtn.setFont(font)
        self.Dbtn.setFlat(True)
        self.Dbtn.setObjectName("Dbtn")
        self.Ebtn = QtWidgets.QPushButton(self.centralwidget)
        self.Ebtn.setGeometry(QtCore.QRect(500, 10, 51, 51))
        self.Ebtn.setFont(font)
        self.Ebtn.setFlat(True)
        self.Ebtn.setObjectName("Ebtn")
        self.EObtn = QtWidgets.QPushButton(self.centralwidget)
        self.EObtn.setGeometry(QtCore.QRect(550, 10, 51, 51))
        self.EObtn.setFont(font)
        self.EObtn.setFlat(True)
        self.EObtn.setObjectName("EObtn")
        self.ZHbtn = QtWidgets.QPushButton(self.centralwidget)
        self.ZHbtn.setGeometry(QtCore.QRect(600, 10, 51, 51))
        self.ZHbtn.setFont(font)
        self.ZHbtn.setFlat(True)
        self.ZHbtn.setObjectName("ZHbtn")
        self.Zbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Zbtn.setGeometry(QtCore.QRect(650, 10, 51, 51))
        self.Zbtn.setFont(font)
        self.Zbtn.setFlat(True)
        self.Zbtn.setObjectName("Zbtn")
        self.Ibtn = QtWidgets.QPushButton(self.centralwidget)
        self.Ibtn.setGeometry(QtCore.QRect(700, 10, 51, 51))
        self.Ibtn.setFont(font)
        self.Ibtn.setFlat(True)
        self.Ibtn.setObjectName("Ibtn")
        self.Jbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Jbtn.setGeometry(QtCore.QRect(750, 10, 51, 51))
        self.Jbtn.setFont(font)
        self.Jbtn.setFlat(True)
        self.Jbtn.setObjectName("Jbtn")
        self.Obtn = QtWidgets.QPushButton(self.centralwidget)
        self.Obtn.setGeometry(QtCore.QRect(450, 60, 51, 51))
        self.Obtn.setFont(font)
        self.Obtn.setFlat(True)
        self.Obtn.setObjectName("Obtn")
        self.Fbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Fbtn.setGeometry(QtCore.QRect(750, 60, 51, 51))
        self.Fbtn.setFont(font)
        self.Fbtn.setFlat(True)
        self.Fbtn.setObjectName("Fbtn")
        self.Lbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Lbtn.setGeometry(QtCore.QRect(300, 60, 51, 51))
        self.Lbtn.setFont(font)
        self.Lbtn.setFlat(True)
        self.Lbtn.setObjectName("Lbtn")
        self.Mbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Mbtn.setGeometry(QtCore.QRect(350, 60, 51, 51))
        self.Mbtn.setFont(font)
        self.Mbtn.setFlat(True)
        self.Mbtn.setObjectName("Mbtn")
        self.Rbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Rbtn.setGeometry(QtCore.QRect(550, 60, 51, 51))
        self.Rbtn.setFont(font)
        self.Rbtn.setFlat(True)
        self.Rbtn.setObjectName("Rbtn")
        self.Tbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Tbtn.setGeometry(QtCore.QRect(650, 60, 51, 51))
        self.Tbtn.setFont(font)
        self.Tbtn.setFlat(True)
        self.Tbtn.setObjectName("Tbtn")
        self.Nbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Nbtn.setGeometry(QtCore.QRect(400, 60, 51, 51))
        self.Nbtn.setFont(font)
        self.Nbtn.setFlat(True)
        self.Nbtn.setObjectName("Nbtn")
        self.Kbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Kbtn.setGeometry(QtCore.QRect(250, 60, 51, 51))
        self.Kbtn.setFont(font)
        self.Kbtn.setFlat(True)
        self.Kbtn.setObjectName("Kbtn")
        self.Pbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Pbtn.setGeometry(QtCore.QRect(500, 60, 51, 51))
        self.Pbtn.setFont(font)
        self.Pbtn.setFlat(True)
        self.Pbtn.setObjectName("Pbtn")
        self.Sbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Sbtn.setGeometry(QtCore.QRect(600, 60, 51, 51))
        self.Sbtn.setFont(font)
        self.Sbtn.setFlat(True)
        self.Sbtn.setObjectName("Sbtn")
        self.Ubtn = QtWidgets.QPushButton(self.centralwidget)
        self.Ubtn.setGeometry(QtCore.QRect(700, 60, 51, 51))
        self.Ubtn.setFont(font)
        self.Ubtn.setFlat(True)
        self.Ubtn.setObjectName("Ubtn")
        self.SCHbtn = QtWidgets.QPushButton(self.centralwidget)
        self.SCHbtn.setGeometry(QtCore.QRect(450, 110, 51, 51))
        self.SCHbtn.setFont(font)
        self.SCHbtn.setFlat(True)
        self.SCHbtn.setObjectName("SCHbtn")
        self.YAbtn = QtWidgets.QPushButton(self.centralwidget)
        self.YAbtn.setGeometry(QtCore.QRect(750, 110, 51, 51))
        self.YAbtn.setFont(font)
        self.YAbtn.setFlat(True)
        self.YAbtn.setObjectName("YAbtn")
        self.Cbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Cbtn.setGeometry(QtCore.QRect(300, 110, 51, 51))
        self.Cbtn.setFont(font)
        self.Cbtn.setFlat(True)
        self.Cbtn.setObjectName("Cbtn")
        self.CHbtn = QtWidgets.QPushButton(self.centralwidget)
        self.CHbtn.setGeometry(QtCore.QRect(350, 110, 51, 51))
        self.CHbtn.setFont(font)
        self.CHbtn.setFlat(True)
        self.CHbtn.setObjectName("CHbtn")
        self.YYbtn = QtWidgets.QPushButton(self.centralwidget)
        self.YYbtn.setGeometry(QtCore.QRect(550, 110, 51, 51))
        self.YYbtn.setFont(font)
        self.YYbtn.setFlat(True)
        self.YYbtn.setObjectName("YYbtn")
        self.AEbtn = QtWidgets.QPushButton(self.centralwidget)
        self.AEbtn.setGeometry(QtCore.QRect(650, 110, 51, 51))
        self.AEbtn.setFont(font)
        self.AEbtn.setFlat(True)
        self.AEbtn.setObjectName("AEbtn")
        self.SHbtn = QtWidgets.QPushButton(self.centralwidget)
        self.SHbtn.setGeometry(QtCore.QRect(400, 110, 51, 51))
        self.SHbtn.setFont(font)
        self.SHbtn.setFlat(True)
        self.SHbtn.setObjectName("SHbtn")
        self.Hbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Hbtn.setGeometry(QtCore.QRect(250, 110, 51, 51))
        self.Hbtn.setFont(font)
        self.Hbtn.setFlat(True)
        self.Hbtn.setObjectName("Hbtn")
        self.TVERDbtn = QtWidgets.QPushButton(self.centralwidget)
        self.TVERDbtn.setGeometry(QtCore.QRect(500, 110, 51, 51))
        self.TVERDbtn.setFont(font)
        self.TVERDbtn.setFlat(True)
        self.TVERDbtn.setObjectName("TVERDbtn")
        self.MYAGKbtn = QtWidgets.QPushButton(self.centralwidget)
        self.MYAGKbtn.setGeometry(QtCore.QRect(600, 110, 51, 51))
        self.MYAGKbtn.setFont(font)
        self.MYAGKbtn.setFlat(True)
        self.MYAGKbtn.setObjectName("MYAGKbtn")
        self.YUbtn = QtWidgets.QPushButton(self.centralwidget)
        self.YUbtn.setGeometry(QtCore.QRect(700, 110, 51, 51))
        self.YUbtn.setFont(font)
        self.YUbtn.setFlat(True)
        self.YUbtn.setObjectName("YUbtn")
        self.diffstat = QtWidgets.QLabel(self.centralwidget)
        self.diffstat.setGeometry(QtCore.QRect(30, 10, 191, 101))
        font.setPointSize(20)
        self.diffstat.setFont(font)
        self.diffstat.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignLeft)
        self.diffstat.setObjectName("diffstat")
        self.hidedown = QtWidgets.QLabel(self.centralwidget)
        self.hidedown.setGeometry(QtCore.QRect(-10, 670, 1091, 131))
        self.hidedown.setPixmap(QtGui.QPixmap("ocean.jpg"))
        self.hidedown.setObjectName("hidedown")
        self.hideup = QtWidgets.QLabel(self.centralwidget)
        self.hideup.setGeometry(QtCore.QRect(10, 20, 1061, 211))
        self.hideup.setPixmap(QtGui.QPixmap("sky.jpg"))
        self.hideup.setObjectName("hideup")
        self.backgrlabel = QtWidgets.QLabel(self.centralwidget)
        self.backgrlabel.setGeometry(QtCore.QRect(0, 0, 1081, 801))
        self.backgrlabel.setPixmap(QtGui.QPixmap("bck1.jpg"))
        self.backgrlabel.setObjectName("backgrlabel")

        '''спавн всего'''
        self.backgrlabel.raise_()
        self.wordstat.raise_()
        self.help5050.raise_()
        self.helps.raise_()
        self.tryletter.raise_()
        self.numstr1.raise_()
        self.numstr2.raise_()
        self.numstr3.raise_()
        self.trystat.raise_()
        self.Abtn.raise_()
        self.Bbtn.raise_()
        self.Vbtn.raise_()
        self.Gbtn.raise_()
        self.Dbtn.raise_()
        self.Ebtn.raise_()
        self.EObtn.raise_()
        self.ZHbtn.raise_()
        self.Zbtn.raise_()
        self.Ibtn.raise_()
        self.Jbtn.raise_()
        self.Obtn.raise_()
        self.Fbtn.raise_()
        self.Lbtn.raise_()
        self.Mbtn.raise_()
        self.Rbtn.raise_()
        self.Tbtn.raise_()
        self.Nbtn.raise_()
        self.Kbtn.raise_()
        self.Pbtn.raise_()
        self.Sbtn.raise_()
        self.Ubtn.raise_()
        self.SCHbtn.raise_()
        self.YAbtn.raise_()
        self.Cbtn.raise_()
        self.CHbtn.raise_()
        self.YYbtn.raise_()
        self.AEbtn.raise_()
        self.SHbtn.raise_()
        self.Hbtn.raise_()
        self.TVERDbtn.raise_()
        self.MYAGKbtn.raise_()
        self.YUbtn.raise_()
        self.diffstat.raise_()
        self.hidedown.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.normbtn.raise_()
        self.difftext.raise_()
        self.choosedif.raise_()
        self.hardbtn.raise_()
        self.easybtn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        '''создание слова'''
        with open('слова.txt', 'r', encoding='UTF-8') as f:
            correct_ones = []
            words_list = f.read().split('\n')
            random_num = random.randint(0, (len(words_list) - 1))
            word1 = list(words_list[random_num].upper())
            word = ''.join(word1)
        for i in range(len(word1)):
            correct_ones.append('_ ')
        lines = ''.join(correct_ones)
        _translate = QtCore.QCoreApplication.translate
        self.wordstat.setText(_translate("MainWindow", lines))

        self.retranslateUi(MainWindow)
        self.numstr1.clicked.connect(self.numstr1.hide)
        self.numstr1.clicked.connect(lambda: self.help(word1, self.wordstat.text(), 1))
        self.numstr2.clicked.connect(self.numstr2.hide)
        self.numstr2.clicked.connect(lambda: self.help(word1, self.wordstat.text(), 1))
        self.numstr3.clicked.connect(self.numstr3.hide)
        self.numstr3.clicked.connect(lambda: self.help(word1, self.wordstat.text(), 1))
        self.tryletter.clicked.connect(self.tryletter.hide)
        self.tryletter.clicked.connect(lambda: self.help(word1, self.wordstat.text(), 2))
        self.help5050.clicked.connect(self.help5050.hide)
        self.help5050.clicked.connect(lambda: self.help(word1, self.wordstat.text(), 13))
        self.easybtn.clicked.connect(self.choosedif.hide)
        self.easybtn.clicked.connect(lambda: self.rename("сложность:\n" + self.easybtn.text()))
        self.easybtn.clicked.connect(lambda: self.lifes("попыток: 10"))
        self.easybtn.clicked.connect(self.normbtn.hide)
        self.easybtn.clicked.connect(self.hardbtn.hide)
        self.easybtn.clicked.connect(self.difftext.hide)
        self.easybtn.clicked.connect(self.easybtn.hide)
        self.normbtn.clicked.connect(self.choosedif.hide)
        self.normbtn.clicked.connect(lambda: self.rename("сложность:\n" + self.normbtn.text()))
        self.normbtn.clicked.connect(lambda: self.lifes("попыток: 10"))
        self.normbtn.clicked.connect(self.easybtn.hide)
        self.normbtn.clicked.connect(self.hardbtn.hide)
        self.normbtn.clicked.connect(self.difftext.hide)
        self.normbtn.clicked.connect(self.normbtn.hide)
        self.hardbtn.clicked.connect(self.hardbtn.hide)
        self.hardbtn.clicked.connect(lambda: self.rename("сложность:\n" + self.hardbtn.text()))
        self.hardbtn.clicked.connect(lambda: self.lifes("попыток: 5"))
        self.hardbtn.clicked.connect(self.choosedif.hide)
        self.hardbtn.clicked.connect(self.normbtn.hide)
        self.hardbtn.clicked.connect(self.easybtn.hide)
        self.hardbtn.clicked.connect(self.difftext.hide)
        self.easybtn.clicked.connect(self.label.hide)
        self.normbtn.clicked.connect(self.label.hide)
        self.hardbtn.clicked.connect(self.label.hide)
        '''буковки'''
        self.Abtn.clicked.connect(self.Abtn.hide)
        self.Abtn.clicked.connect(lambda: self.play(self.Abtn.text(), word, correct_ones))
        self.Bbtn.clicked.connect(self.Bbtn.hide)
        self.Bbtn.clicked.connect(lambda: self.play(self.Bbtn.text(), word, correct_ones))
        self.Vbtn.clicked.connect(self.Vbtn.hide)
        self.Vbtn.clicked.connect(lambda: self.play(self.Vbtn.text(), word, correct_ones))
        self.Gbtn.clicked.connect(self.Gbtn.hide)
        self.Gbtn.clicked.connect(lambda: self.play(self.Gbtn.text(), word, correct_ones))
        self.Dbtn.clicked.connect(self.Dbtn.hide)
        self.Dbtn.clicked.connect(lambda: self.play(self.Dbtn.text(), word, correct_ones))
        self.Ebtn.clicked.connect(self.Ebtn.hide)
        self.Ebtn.clicked.connect(lambda: self.play(self.Ebtn.text(), word, correct_ones))
        self.EObtn.clicked.connect(self.EObtn.hide)
        self.EObtn.clicked.connect(lambda: self.play(self.EObtn.text(), word, correct_ones))
        self.ZHbtn.clicked.connect(self.ZHbtn.hide)
        self.ZHbtn.clicked.connect(lambda: self.play(self.ZHbtn.text(), word, correct_ones))
        self.Zbtn.clicked.connect(self.Zbtn.hide)
        self.Zbtn.clicked.connect(lambda: self.play(self.Zbtn.text(), word, correct_ones))
        self.Ibtn.clicked.connect(self.Ibtn.hide)
        self.Ibtn.clicked.connect(lambda: self.play(self.Ibtn.text(), word, correct_ones))
        self.Jbtn.clicked.connect(self.Jbtn.hide)
        self.Jbtn.clicked.connect(lambda: self.play(self.Jbtn.text(), word, correct_ones))
        self.Kbtn.clicked.connect(self.Kbtn.hide)
        self.Kbtn.clicked.connect(lambda: self.play(self.Kbtn.text(), word, correct_ones))
        self.Lbtn.clicked.connect(self.Lbtn.hide)
        self.Lbtn.clicked.connect(lambda: self.play(self.Lbtn.text(), word, correct_ones))
        self.Mbtn.clicked.connect(self.Mbtn.hide)
        self.Mbtn.clicked.connect(lambda: self.play(self.Mbtn.text(), word, correct_ones))
        self.Nbtn.clicked.connect(self.Nbtn.hide)
        self.Nbtn.clicked.connect(lambda: self.play(self.Nbtn.text(), word, correct_ones))
        self.Obtn.clicked.connect(self.Obtn.hide)
        self.Obtn.clicked.connect(lambda: self.play(self.Obtn.text(), word, correct_ones))
        self.Pbtn.clicked.connect(self.Pbtn.hide)
        self.Pbtn.clicked.connect(lambda: self.play(self.Pbtn.text(), word, correct_ones))
        self.Rbtn.clicked.connect(self.Rbtn.hide)
        self.Rbtn.clicked.connect(lambda: self.play(self.Rbtn.text(), word, correct_ones))
        self.Sbtn.clicked.connect(self.Sbtn.hide)
        self.Sbtn.clicked.connect(lambda: self.play(self.Sbtn.text(), word, correct_ones))
        self.Tbtn.clicked.connect(self.Tbtn.hide)
        self.Tbtn.clicked.connect(lambda: self.play(self.Tbtn.text(), word, correct_ones))
        self.Ubtn.clicked.connect(self.Ubtn.hide)
        self.Ubtn.clicked.connect(lambda: self.play(self.Ubtn.text(), word, correct_ones))
        self.Fbtn.clicked.connect(self.Fbtn.hide)
        self.Fbtn.clicked.connect(lambda: self.play(self.Fbtn.text(), word, correct_ones))
        self.Hbtn.clicked.connect(self.Hbtn.hide)
        self.Hbtn.clicked.connect(lambda: self.play(self.Hbtn.text(), word, correct_ones))
        self.Cbtn.clicked.connect(self.Cbtn.hide)
        self.Cbtn.clicked.connect(lambda: self.play(self.Cbtn.text(), word, correct_ones))
        self.CHbtn.clicked.connect(self.CHbtn.hide)
        self.CHbtn.clicked.connect(lambda: self.play(self.CHbtn.text(), word, correct_ones))
        self.SHbtn.clicked.connect(self.SHbtn.hide)
        self.SHbtn.clicked.connect(lambda: self.play(self.SHbtn.text(), word, correct_ones))
        self.SCHbtn.clicked.connect(self.SCHbtn.hide)
        self.SCHbtn.clicked.connect(lambda: self.play(self.SCHbtn.text(), word, correct_ones))
        self.TVERDbtn.clicked.connect(self.TVERDbtn.hide)
        self.TVERDbtn.clicked.connect(lambda: self.play(self.TVERDbtn.text(), word, correct_ones))
        self.YYbtn.clicked.connect(self.YYbtn.hide)
        self.YYbtn.clicked.connect(lambda: self.play(self.YYbtn.text(), word, correct_ones))
        self.MYAGKbtn.clicked.connect(self.MYAGKbtn.hide)
        self.MYAGKbtn.clicked.connect(lambda: self.play(self.MYAGKbtn.text(), word, correct_ones))
        self.AEbtn.clicked.connect(self.AEbtn.hide)
        self.AEbtn.clicked.connect(lambda: self.play(self.AEbtn.text(), word, correct_ones))
        self.YUbtn.clicked.connect(self.YUbtn.hide)
        self.YUbtn.clicked.connect(lambda: self.play(self.YUbtn.text(), word, correct_ones))
        self.YAbtn.clicked.connect(self.YAbtn.hide)
        self.YAbtn.clicked.connect(lambda: self.play(self.YAbtn.text(), word, correct_ones))
        '''другое'''
        self.normbtn.clicked.connect(self.tryletter.hide)
        self.normbtn.clicked.connect(self.help5050.hide)
        self.easybtn.clicked.connect(self.hidedown.hide)
        self.normbtn.clicked.connect(self.hidedown.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    '''спавн попыток'''
    def lifes(self, text):
        _translate = QtCore.QCoreApplication.translate
        self.trystat.setText(_translate("MainWindow", text))

    '''спавн текстов виджетов и кнопок'''
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.help5050.setText(_translate("MainWindow", "гл|согл"))
        self.helps.setText(_translate("MainWindow", "Подсказки"))
        self.tryletter.setText(_translate("MainWindow", "-попытка, +буква"))
        self.numstr1.setText(_translate("MainWindow", "номер строки"))
        self.numstr2.setText(_translate("MainWindow", "номер строки"))
        self.numstr3.setText(_translate("MainWindow", "номер строки"))
        self.choosedif.setText(_translate("MainWindow", "Выбери сложность:"))
        self.difftext.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">*легкая - все подсказки</p><p align=\"center\">*нормальная - 3 подсказки по строке</p><p align=\"center\">*сложная - без подсказок, меньше жизней</p></body></html>"))
        self.easybtn.setText(_translate("MainWindow", "легкая"))
        self.normbtn.setText(_translate("MainWindow", "нормальная"))
        self.hardbtn.setText(_translate("MainWindow", "сложная"))
        self.Abtn.setText(_translate("MainWindow", "А"))
        self.Bbtn.setText(_translate("MainWindow", "Б"))
        self.Vbtn.setText(_translate("MainWindow", "В"))
        self.Gbtn.setText(_translate("MainWindow", "Г"))
        self.Dbtn.setText(_translate("MainWindow", "Д"))
        self.Ebtn.setText(_translate("MainWindow", "Е"))
        self.EObtn.setText(_translate("MainWindow", "Ё"))
        self.ZHbtn.setText(_translate("MainWindow", "Ж"))
        self.Zbtn.setText(_translate("MainWindow", "З"))
        self.Ibtn.setText(_translate("MainWindow", "И"))
        self.Jbtn.setText(_translate("MainWindow", "Й"))
        self.Obtn.setText(_translate("MainWindow", "О"))
        self.Fbtn.setText(_translate("MainWindow", "Ф"))
        self.Lbtn.setText(_translate("MainWindow", "Л"))
        self.Mbtn.setText(_translate("MainWindow", "М"))
        self.Rbtn.setText(_translate("MainWindow", "Р"))
        self.Tbtn.setText(_translate("MainWindow", "Т"))
        self.Nbtn.setText(_translate("MainWindow", "Н"))
        self.Kbtn.setText(_translate("MainWindow", "К"))
        self.Pbtn.setText(_translate("MainWindow", "П"))
        self.Sbtn.setText(_translate("MainWindow", "С"))
        self.Ubtn.setText(_translate("MainWindow", "У"))
        self.SCHbtn.setText(_translate("MainWindow", "Щ"))
        self.YAbtn.setText(_translate("MainWindow", "Я"))
        self.Cbtn.setText(_translate("MainWindow", "Ц"))
        self.CHbtn.setText(_translate("MainWindow", "Ч"))
        self.YYbtn.setText(_translate("MainWindow", "Ы"))
        self.AEbtn.setText(_translate("MainWindow", "Э"))
        self.SHbtn.setText(_translate("MainWindow", "Ш"))
        self.Hbtn.setText(_translate("MainWindow", "Х"))
        self.TVERDbtn.setText(_translate("MainWindow", "Ъ"))
        self.MYAGKbtn.setText(_translate("MainWindow", "Ь"))
        self.YUbtn.setText(_translate("MainWindow", "Ю"))
        self.diffstat.setText(_translate("MainWindow", "сложность:"))

        '''сама игра'''

    '''спавн сложности'''
    def rename(self, level):
        _translate = QtCore.QCoreApplication.translate
        self.diffstat.setText(_translate("MainWindow", level))

    '''кнопочки помощь'''
    def help(self, word, letters, numb_of_help):
        missed_letters = []
        alph = {'А': 1, 'Б': 2, 'В': 3, 'Г': 4, 'Д': 5, 'Е': 6, 'Ё': 7, 'Ж':8, 'З': 9, 'И': 10, 'Й': 11,
                'К': 12, 'Л': 13, 'М': 14, 'Н': 15, 'О': 16, 'П': 17, 'Р': 18, 'С': 19, 'Т': 20, 'У': 21, 'Ф': 22,
                'Х': 23, 'Ц': 24, 'Ч': 25, 'Ш': 26, 'Щ': 27, 'Ъ': 28, 'Ы': 29, 'Ь':30, 'Э': 31, 'Ю': 32, 'Я': 33}
        v = ['У', 'Е', 'Ы', 'А', 'О', 'Э', 'Я', 'И', 'Ю', 'Ё']
        for a in range(len(word)):
            if word[a] != letters.replace(' ', '')[a]:
                missed_letters.append(word[a])
        rand_num = random.randint(0, (len(missed_letters) - 1))
        guess_letter = missed_letters[rand_num]
        line = guess_letter
        if numb_of_help == 2:
            e = int(self.trystat.text().split()[1]) - 1
            self.trystat.setText("попыток: " + str(e))
        else:
            if 0 < alph[guess_letter] < 12:
                line = '1 ряд'
            if 11 < alph[guess_letter] < 23:
                line = '2 ряд'
            if 22 < alph[guess_letter] < 34:
                line = '3 ряд'
            if numb_of_help == 13:
                if guess_letter in v:
                    line += ', гласная'
                else:
                    line += ', согласная,\nвключая ЬЪ'
        QMessageBox.information(None, "Help", 'Подсказка: ' + line, buttons=QMessageBox.Ok)

    '''окошко "продолжим игру?"'''
    def continue_game(self):
        result = QMessageBox.information(None, "The End", 'Игра окончена!\nПродолжим?',
                                         buttons=QMessageBox.Ok | QMessageBox.No,
                                         defaultButton=QMessageBox.Ok)
        if result == 1024:
            ui.setupUi(MainWindow)
        else:
            sys.exit(0)

    '''спавн нужной картинки'''
    def picture(self, life):
        name = str(life) + 'try.png'
        self.label_2.setPixmap(QtGui.QPixmap(name))

    '''проверка по буковкам'''
    def play(self, letter, word, correct_ones):
        e = int(self.trystat.text().split()[1]) #число жизней
        diff = self.diffstat.text().split('\n')[1] #сложность
        _translate = QtCore.QCoreApplication.translate
        if e > 0:
            if letter in word:
                index_list = []
                for i in range(len(correct_ones)):
                    if word[i] == letter:
                        index_list.append(i)
                for i in index_list:
                    correct_ones[i] = letter.upper()
                t = "".join(correct_ones)
                self.wordstat.setText(t)
                if t.upper() == word:
                    st = "cлово " + t + ".\nУра! Собачка спасена!"
                    self.wordstat.setText(_translate("MainWindow", st))
                    self.continue_game()
            else:
                e = e - 1
                if e > 0:
                    self.trystat.setText("попыток: " + str(e))
                    if diff == "сложная":
                         e = e * 2
                self.picture(e)

        if e == 0:
            self.trystat.setText("попыток: 0")
            st = "cлово " + word + ".\nНе получилось ;с"
            self.wordstat.setText(_translate("MainWindow", st))
            self.picture(e)
            self.continue_game()

x = True
if x:
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())